import jsPDF from "jspdf";
import type { Question } from "../data/types";
import type { Lang } from "../i18n";
import { localize } from "./i18nText";
import { splitInlineCode } from "./inlineCode";

type RGB = readonly [number, number, number];

// A4 geometry, in millimetres.
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_X = 18;
const CONTENT_W = PAGE_W - MARGIN_X * 2;
const BODY_TOP = 26;
const FOOTER_RULE_Y = PAGE_H - 16;
const BODY_BOTTOM = FOOTER_RULE_Y - 8;

// Left gutter reserved for the question number and the correct-answer ticks,
// so option text stays on a single alignment grid down the whole document.
const GUTTER = 11;
const BODY_X = MARGIN_X + GUTTER;
const BODY_W = CONTENT_W - GUTTER;

// Brand palette, mirroring the --color-* tokens in src/index.css.
const INK: RGB = [20, 20, 43];
const MUTED: RGB = [91, 91, 112];
const TEAL: RGB = [74, 136, 150];
const TEAL_DARK: RGB = [58, 107, 119];
const BROWN: RGB = [125, 78, 46];
const GREEN: RGB = [29, 158, 117];
const GREEN_TINT: RGB = [236, 249, 244];
const SURFACE: RGB = [246, 245, 251];
const HAIRLINE: RGB = [223, 222, 231];

const PT_TO_MM = 25.4 / 72;
const LINE_FACTOR = 1.32;
const lineHeight = (size: number) => size * PT_TO_MM * LINE_FACTOR;

const OPTION_LETTERS = "ABCDEFGH";

/**
 * jsPDF's built-in fonts only speak WinAnsi. A single character outside it (an
 * arrow, a tick, a circled digit) silently switches the whole string to a
 * two-byte encoding, which prints as s p a c e d - o u t letters *and* breaks
 * the width measurement so lines overflow the page. Everything drawn goes
 * through `clean()` first.
 */
const SUBSTITUTIONS: [RegExp, string][] = [
  [/[→⇒]/g, "->"],
  [/[←⇐]/g, "<-"],
  [/[✓✔]/g, ""],
  [/[✗✘]/g, "x"],
  [/≥/g, ">="],
  [/≤/g, "<="],
  [/≠/g, "!="],
  [/≡/g, "="],
  [/≈/g, "~"],
  [/…/g, "..."],
  // The blank placeholder in fill-in-the-expression questions.
  [/⬚/g, "____"],
  [/⣿/g, ""],
];

// Circled digits ①-⑳ (U+2460-U+2473, "1" through "20") used elsewhere in the
// app (see withCircledNumbers) to number sub-parts of a question - handled
// as a range rather than hardcoding a handful, so a question needing more
// than the first few doesn't silently lose that digit to clean()'s WinAnsi
// filter below (it'd just vanish as a stripped space instead of "(6)", "(7)"...).
function expandCircledDigits(text: string): string {
  return text.replace(/[①-⑳]/g, (ch) => `(${ch.codePointAt(0)! - 0x2460 + 1})`);
}

// Characters above U+00FF that WinAnsi still covers.
const WINANSI_EXTRAS =
  "€‚ƒ„…†‡ˆ‰Š‹ŒŽ" +
  "‘’“”•–-˜™š›œžŸ";

function clean(text: string): string {
  let out = expandCircledDigits(text);
  for (const [pattern, replacement] of SUBSTITUTIONS) out = out.replace(pattern, replacement);
  return Array.from(out)
    .map((ch) => (ch.charCodeAt(0) <= 0xff || WINANSI_EXTRAS.includes(ch) ? ch : " "))
    .join("")
    .replace(/ {3,}/g, "  ")
    .trim();
}

const COPY = {
  fr: {
    subtitle: "Questions d'entraînement avec corrigé",
    questionsLabel: (n: number) => `${n} question${n > 1 ? "s" : ""}`,
    generatedOn: "Généré le",
    answerKey: "Corrigé inclus",
    selectN: (n: number) => `${n} bonnes réponses attendues`,
    orderLabel: "Ordre correct",
    matchLabel: "Associations correctes",
    hotspotLabel: "Réponses correctes",
    explanation: "Explication",
    footerNote: "Document généré par Lampas .ai",
  },
  en: {
    subtitle: "Practice questions with answer key",
    questionsLabel: (n: number) => `${n} question${n > 1 ? "s" : ""}`,
    generatedOn: "Generated on",
    answerKey: "Answer key included",
    selectN: (n: number) => `${n} correct answers expected`,
    orderLabel: "Correct order",
    matchLabel: "Correct matches",
    hotspotLabel: "Correct answers",
    explanation: "Explanation",
    footerNote: "Document generated by Lampas .ai",
  },
} as const;

/**
 * "<slot> : <answer>" for match/hotspot rows. Labels often already end in a
 * colon or an arrow of their own, so the trailing punctuation is dropped and a
 * distinct separator is used to keep the answer unambiguous.
 */
function slotAnswer(label: string, answer: string): string {
  const trimmed = label.replace(/[\s:]+$/, "");
  return trimmed ? `${trimmed} : ${answer}` : answer;
}

function fileSlug(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function exportCertificationPdf(certName: string, questions: Question[], lang: Lang) {
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const t = COPY[lang];
  const title = clean(certName);

  doc.setLineHeightFactor(LINE_FACTOR);
  doc.setProperties({
    title: `Lampas .ai - ${title}`,
    subject: t.subtitle,
    author: "Lampas .ai",
    creator: "Lampas .ai",
  });

  let y = 0;

  const setFill = (c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
  const setText = (c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
  const setDraw = (c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);

  type RichToken = { text: string; code: boolean; underline: boolean };

  // Sentinel pair marking an underlined span within text passed to
  // writeRich/measureRich - used to underline just the answer merged into a
  // fill-in-the-blank sentence (see the hotspot branch in questionBlock).
  // Control characters, never drawn literally - stripped out while tokenizing.
  const UNDERLINE_START = "";
  const UNDERLINE_END = "";

  // Tokenizes text (already split into prose/code segments by
  // splitInlineCode, and underline/UNDERLINE_END spans by the caller) into
  // words and whitespace runs, each tagged with whether it belongs to a
  // formula-like fragment - so wrapping can measure and draw each token in
  // the right font (courier for code, helvetica otherwise) and underline
  // style.
  function tokenizeRich(text: string): RichToken[] {
    const tokens: RichToken[] = [];
    const pushSegments = (chunk: string, underline: boolean) => {
      for (const seg of splitInlineCode(chunk)) {
        for (const part of seg.text.split(/(\s+)/)) {
          if (part.length > 0) tokens.push({ text: part, code: seg.code, underline });
        }
      }
    };
    const underlineParts = text.split(UNDERLINE_START);
    pushSegments(underlineParts[0], false);
    for (let i = 1; i < underlineParts.length; i++) {
      const [underlined, rest = ""] = underlineParts[i].split(UNDERLINE_END);
      pushSegments(underlined, true);
      pushSegments(rest, false);
    }
    return tokens;
  }

  function fontFor(code: boolean): "helvetica" | "courier" {
    return code ? "courier" : "helvetica";
  }

  // Wraps `text` into lines of tokens, sharing this single layout pass
  // between measureRich (for `ensure()` pagination) and writeRich (the
  // actual draw), so the two can never disagree on line count.
  function layoutRich(
    text: string,
    width: number,
    size: number,
    style: "normal" | "bold" | "italic"
  ): RichToken[][] {
    const widthOf = (t: RichToken) => {
      doc.setFont(fontFor(t.code), style);
      doc.setFontSize(size);
      return doc.getTextWidth(t.text);
    };
    const lines: RichToken[][] = [[]];
    let cursor = 0;
    for (const token of tokenizeRich(text)) {
      const currentLine = lines[lines.length - 1];
      const isSpace = /^\s+$/.test(token.text);
      if (isSpace && currentLine.length === 0) continue; // never start a line with a space
      const w = widthOf(token);
      if (cursor > 0 && cursor + w > width) {
        lines.push([]);
        cursor = 0;
        if (isSpace) continue; // dropped at the wrap point
      }
      lines[lines.length - 1].push(token);
      cursor += w;
    }
    return lines;
  }

  function measureRich(text: string, width: number, size: number, style: "normal" | "bold" | "italic") {
    return layoutRich(text, width, size, style).length * lineHeight(size);
  }

  function newPage() {
    doc.addPage();
    y = BODY_TOP;
  }

  function ensure(height: number) {
    if (y + height > BODY_BOTTOM) newPage();
  }

  /** Draws wrapped text with `y` as its top edge, and advances `y`. */
  function write(
    text: string,
    opts: {
      x?: number;
      width?: number;
      size?: number;
      style?: "normal" | "bold" | "italic";
      color?: RGB;
      gapAfter?: number;
    } = {}
  ) {
    const {
      x = BODY_X,
      width = BODY_W,
      size = 10.5,
      style = "normal",
      color = INK,
      gapAfter = 0,
    } = opts;
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    setText(color);
    const lines = doc.splitTextToSize(text, width) as string[];
    doc.text(lines, x, y, { baseline: "top" });
    y += lines.length * lineHeight(size) + gapAfter;
  }

  /** Like `write`, but renders inline formula-like fragments in monospace. */
  function writeRich(
    text: string,
    opts: {
      x?: number;
      width?: number;
      size?: number;
      style?: "normal" | "bold" | "italic";
      color?: RGB;
      gapAfter?: number;
    } = {}
  ) {
    const {
      x = BODY_X,
      width = BODY_W,
      size = 10.5,
      style = "normal",
      color = INK,
      gapAfter = 0,
    } = opts;
    setText(color);
    for (const line of layoutRich(text, width, size, style)) {
      let cx = x;
      for (const token of line) {
        doc.setFont(fontFor(token.code), style);
        doc.setFontSize(size);
        doc.text(token.text, cx, y, { baseline: "top" });
        const w = doc.getTextWidth(token.text);
        if (token.underline) {
          setDraw(color);
          doc.setLineWidth(0.2);
          const underlineY = y + size * PT_TO_MM * 0.92;
          doc.line(cx, underlineY, cx + w, underlineY);
        }
        cx += w;
      }
      y += lineHeight(size);
    }
    y += gapAfter;
  }

  /** Approximates the brand gradient (teal -> brown) with thin vertical slices. */
  function brandBar(top: number, height: number) {
    const steps = 64;
    const sliceW = PAGE_W / steps;
    for (let i = 0; i < steps; i++) {
      const ratio = i / (steps - 1);
      doc.setFillColor(
        Math.round(TEAL[0] + (BROWN[0] - TEAL[0]) * ratio),
        Math.round(TEAL[1] + (BROWN[1] - TEAL[1]) * ratio),
        Math.round(TEAL[2] + (BROWN[2] - TEAL[2]) * ratio)
      );
      doc.rect(i * sliceW, top, sliceW + 0.25, height, "F");
    }
  }

  function tick(centerX: number, centerY: number) {
    setDraw(GREEN);
    doc.setLineWidth(0.55);
    doc.line(centerX - 1.3, centerY + 0.1, centerX - 0.35, centerY + 1.1);
    doc.line(centerX - 0.35, centerY + 1.1, centerX + 1.45, centerY - 1.5);
  }

  function coverHeader() {
    brandBar(0, 3.5);

    y = 22;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    setText(TEAL_DARK);
    // No charSpace here (or on any other label in this file) - jsPDF emits
    // tracked/letter-spaced text as one separate text-show operator per
    // character, which draws fine but makes the text unreadable if it's
    // ever copy-pasted or extracted (e.g. "L a m p a s . a i" instead of
    // "Lampas .ai") - confirmed with a real text-extraction pass over a
    // generated PDF. Plain text only, everywhere.
    doc.text("Lampas .ai", MARGIN_X, y, { baseline: "top" });

    y += 11;
    write(title, { x: MARGIN_X, width: CONTENT_W, size: 19, style: "bold", color: INK, gapAfter: 3 });
    write(t.subtitle, {
      x: MARGIN_X,
      width: CONTENT_W,
      size: 11,
      color: MUTED,
      gapAfter: 6,
    });

    // Meta strip: question count, answer-key badge, generation date.
    const date = new Date().toLocaleDateString(lang === "fr" ? "fr-FR" : "en-GB", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });
    const meta = clean(
      `${t.questionsLabel(questions.length)}  ·  ${t.answerKey}  ·  ${t.generatedOn} ${date}`
    );
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setText(MUTED);
    doc.text(meta, MARGIN_X, y, { baseline: "top" });
    y += lineHeight(9) + 5;

    setDraw(HAIRLINE);
    doc.setLineWidth(0.3);
    doc.line(MARGIN_X, y, PAGE_W - MARGIN_X, y);
    y += 9;
  }

  function answerTypeLabel(text: string) {
    const size = 8;
    ensure(lineHeight(size) + 2);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    setText(TEAL_DARK);
    doc.text(clean(text).toUpperCase(), BODY_X, y, { baseline: "top" });
    y += lineHeight(size) + 1.8;
  }

  /** One answer row: letter, wrapped text, and a green highlight when correct. */
  function answerRow(label: string, text: string, correct: boolean) {
    const size = 10;
    const labelW = 6.5;
    const padX = 2.5;
    const padY = 1.6;
    const textX = BODY_X + labelW;
    const textW = BODY_W - labelW - padX;

    const height = measureRich(text, textW, size, correct ? "bold" : "normal") + padY * 2;
    ensure(height);

    if (correct) {
      setFill(GREEN_TINT);
      doc.rect(BODY_X - padX, y, BODY_W + padX, height, "F");
      setFill(GREEN);
      doc.rect(BODY_X - padX, y, 0.9, height, "F");
      tick(MARGIN_X + 3.5, y + padY + lineHeight(size) * 0.45);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    setText(correct ? GREEN : MUTED);
    doc.text(label, BODY_X, y + padY, { baseline: "top" });

    const before = y;
    y += padY;
    writeRich(text, {
      x: textX,
      width: textW,
      size,
      style: correct ? "bold" : "normal",
      color: correct ? GREEN : INK,
    });
    y = before + height;
  }

  function explanationBox(text: string) {
    const size = 9;
    const padX = 4;
    const padY = 3;
    const innerW = BODY_W - padX * 2;
    const labelH = lineHeight(7.5) + 1.2;
    const height = labelH + measureRich(text, innerW, size, "italic") + padY * 2;

    ensure(height + 2);
    y += 2;

    setFill(SURFACE);
    doc.rect(BODY_X, y, BODY_W, height, "F");
    setFill(TEAL);
    doc.rect(BODY_X, y, 0.9, height, "F");

    const top = y;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    setText(TEAL_DARK);
    doc.text(clean(t.explanation).toUpperCase(), BODY_X + padX, top + padY, {
      baseline: "top",
    });

    y = top + padY + labelH;
    writeRich(text, { x: BODY_X + padX, width: innerW, size, style: "italic", color: MUTED });
    y = top + height;
  }

  function questionBlock(question: Question, index: number) {
    const number = String(index + 1).padStart(2, "0");
    const heading = clean(localize(question.question, lang));
    const headingH = measureRich(heading, BODY_W, 10.5, "bold");

    // Keep the number, the question and at least one answer row together.
    ensure(headingH + 16);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    setText(TEAL);
    doc.text(number, MARGIN_X, y, { baseline: "top" });

    writeRich(heading, { size: 10.5, style: "bold", color: INK, gapAfter: 2.5 });

    if (question.type === "match" && question.pool && question.targets) {
      answerTypeLabel(t.matchLabel);
      question.targets.forEach((target, i) => {
        const label = clean(localize(target.label, lang));
        const value = clean(localize(question.pool![target.correctPoolIndex], lang));
        answerRow(`${i + 1}.`, slotAnswer(label, value), true);
      });
    } else if (question.type === "hotspot" && question.blanks) {
      answerTypeLabel(t.hotspotLabel);
      question.blanks.forEach((blank, i) => {
        const answer = localize(blank.options[blank.correctIndex], lang);
        const rawLabel = blank.label ? localize(blank.label, lang) : "";
        // A label like "L'attrition est ⬚ fois plus élevée..." reads as a
        // fill-in-the-blank sentence - merge the answer into it (underlined)
        // instead of tacking it on after a separator, which would leave the
        // blank marker sitting unfilled in the exported text.
        if (rawLabel.includes("⬚")) {
          const merged = clean(rawLabel.replace("⬚", `${UNDERLINE_START}${answer}${UNDERLINE_END}`));
          answerRow(`${i + 1}.`, merged, true);
        } else {
          const label = rawLabel ? clean(rawLabel) : "";
          answerRow(`${i + 1}.`, slotAnswer(label, clean(answer)), true);
        }
      });
    } else if (question.type === "order" && question.options && question.correctOrder) {
      answerTypeLabel(t.orderLabel);
      question.correctOrder.forEach((optIdx, position) => {
        answerRow(`${position + 1}.`, clean(localize(question.options![optIdx], lang)), true);
      });
    } else if (question.options) {
      const correct = question.correctIndexes ?? [];
      if (correct.length > 1) {
        answerTypeLabel(t.selectN(correct.length));
      }
      question.options.forEach((option, oi) => {
        answerRow(
          `${OPTION_LETTERS[oi] ?? String(oi + 1)}.`,
          clean(localize(option, lang)),
          correct.includes(oi)
        );
      });
    }

    if (question.explanation) {
      explanationBox(clean(localize(question.explanation, lang)));
    }

    y += 8;
  }

  function footers() {
    const total = doc.getNumberOfPages();
    for (let page = 1; page <= total; page++) {
      doc.setPage(page);
      setDraw(HAIRLINE);
      doc.setLineWidth(0.3);
      doc.line(MARGIN_X, FOOTER_RULE_Y, PAGE_W - MARGIN_X, FOOTER_RULE_Y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      setText(MUTED);
      doc.text(clean(`Lampas .ai · ${title}`), MARGIN_X, FOOTER_RULE_Y + 4, {
        baseline: "top",
      });
      doc.text(`${page} / ${total}`, PAGE_W - MARGIN_X, FOOTER_RULE_Y + 4, {
        baseline: "top",
        align: "right",
      });
    }
  }

  coverHeader();
  questions.forEach(questionBlock);
  footers();
  doc.save(`lampasai-${fileSlug(title)}.pdf`);
}
